import type { EntryWithItems, Product, Profile, ChangeType } from "@/lib/types"

const mockProfile: Profile = {
  id: "demo-user",
  owner_slug: "demo",
  display_name: "Acme Labs",
  avatar_url: null,
  created_at: "2024-01-01T00:00:00Z",
}

const mockProduct: Product = {
  id: "demo-product",
  user_id: "demo-user",
  name: "Acme App",
  slug: "acme-app",
  description: "The best productivity app for teams",
  logo_url: null,
  created_at: "2024-01-01T00:00:00Z",
}

const mockEntries: EntryWithItems[] = [
  {
    id: "entry-1",
    product_id: "demo-product",
    title: "Dark Mode & Performance Boost",
    slug: "v2-1-0-dark-mode",
    summary: "Finally! Dark mode is here along with major performance improvements.",
    version: "2.1.0",
    published: true,
    publish_date: "2026-01-05T00:00:00Z",
    created_at: "2026-01-05T00:00:00Z",
    entry_items: [
      {
        id: "item-1",
        entry_id: "entry-1",
        type: "FEATURE" as ChangeType,
        title: "Dark mode support across all screens",
        description: "Toggle between light and dark themes from settings",
        sort_order: 0,
        created_at: "2026-01-05T00:00:00Z",
      },
      {
        id: "item-2",
        entry_id: "entry-1",
        type: "FEATURE" as ChangeType,
        title: "New keyboard shortcuts for power users",
        description: "Press ? anywhere to see available shortcuts",
        sort_order: 1,
        created_at: "2026-01-05T00:00:00Z",
      },
      {
        id: "item-3",
        entry_id: "entry-1",
        type: "IMPROVEMENT" as ChangeType,
        title: "50% faster page load times",
        description: "Optimized bundle size and lazy loading",
        sort_order: 2,
        created_at: "2026-01-05T00:00:00Z",
      },
      {
        id: "item-4",
        entry_id: "entry-1",
        type: "FIX" as ChangeType,
        title: "Fixed notification sounds not playing on mobile",
        description: null,
        sort_order: 3,
        created_at: "2026-01-05T00:00:00Z",
      },
    ],
  },
  {
    id: "entry-2",
    product_id: "demo-product",
    title: "Team Collaboration Update",
    slug: "v2-0-0-team-collaboration",
    summary: "Real-time collaboration features for teams of all sizes.",
    version: "2.0.0",
    published: true,
    publish_date: "2025-12-15T00:00:00Z",
    created_at: "2025-12-15T00:00:00Z",
    entry_items: [
      {
        id: "item-5",
        entry_id: "entry-2",
        type: "FEATURE" as ChangeType,
        title: "Real-time collaborative editing",
        description: "See teammates' cursors and changes as they happen",
        sort_order: 0,
        created_at: "2025-12-15T00:00:00Z",
      },
      {
        id: "item-6",
        entry_id: "entry-2",
        type: "FEATURE" as ChangeType,
        title: "Team workspaces with role-based permissions",
        description: "Admin, Editor, and Viewer roles",
        sort_order: 1,
        created_at: "2025-12-15T00:00:00Z",
      },
      {
        id: "item-7",
        entry_id: "entry-2",
        type: "BREAKING" as ChangeType,
        title: "API v1 endpoints deprecated",
        description: "Please migrate to API v2 by March 2026",
        sort_order: 2,
        created_at: "2025-12-15T00:00:00Z",
      },
      {
        id: "item-8",
        entry_id: "entry-2",
        type: "IMPROVEMENT" as ChangeType,
        title: "Redesigned dashboard with better analytics",
        description: null,
        sort_order: 3,
        created_at: "2025-12-15T00:00:00Z",
      },
      {
        id: "item-9",
        entry_id: "entry-2",
        type: "FIX" as ChangeType,
        title: "Fixed timezone issues in scheduled tasks",
        description: null,
        sort_order: 4,
        created_at: "2025-12-15T00:00:00Z",
      },
    ],
  },
  {
    id: "entry-3",
    product_id: "demo-product",
    title: "Bug Fixes & Stability",
    slug: "v1-9-5-bug-fixes",
    summary: "Various bug fixes and stability improvements.",
    version: "1.9.5",
    published: true,
    publish_date: "2025-12-01T00:00:00Z",
    created_at: "2025-12-01T00:00:00Z",
    entry_items: [
      {
        id: "item-10",
        entry_id: "entry-3",
        type: "FIX" as ChangeType,
        title: "Fixed crash when opening large files",
        description: "Files over 10MB now load progressively",
        sort_order: 0,
        created_at: "2025-12-01T00:00:00Z",
      },
      {
        id: "item-11",
        entry_id: "entry-3",
        type: "FIX" as ChangeType,
        title: "Resolved sync conflicts in offline mode",
        description: null,
        sort_order: 1,
        created_at: "2025-12-01T00:00:00Z",
      },
      {
        id: "item-12",
        entry_id: "entry-3",
        type: "KNOWNISSUE" as ChangeType,
        title: "Export to PDF may timeout for documents over 100 pages",
        description: "We are working on a fix for the next release",
        sort_order: 2,
        created_at: "2025-12-01T00:00:00Z",
      },
      {
        id: "item-13",
        entry_id: "entry-3",
        type: "NOTE" as ChangeType,
        title: "This is the last release supporting iOS 14",
        description: "Please update to iOS 15+ for future updates",
        sort_order: 3,
        created_at: "2025-12-01T00:00:00Z",
      },
    ],
  },
  {
    id: "entry-4",
    product_id: "demo-product",
    title: "Mobile App Launch",
    slug: "v1-9-0-mobile-launch",
    summary: "Native mobile apps are finally here!",
    version: "1.9.0",
    published: true,
    publish_date: "2025-11-10T00:00:00Z",
    created_at: "2025-11-10T00:00:00Z",
    entry_items: [
      {
        id: "item-14",
        entry_id: "entry-4",
        type: "FEATURE" as ChangeType,
        title: "Native iOS app available on App Store",
        description: "Optimized for iPhone and iPad",
        sort_order: 0,
        created_at: "2025-11-10T00:00:00Z",
      },
      {
        id: "item-15",
        entry_id: "entry-4",
        type: "FEATURE" as ChangeType,
        title: "Native Android app available on Play Store",
        description: "Supports Android 10 and above",
        sort_order: 1,
        created_at: "2025-11-10T00:00:00Z",
      },
      {
        id: "item-16",
        entry_id: "entry-4",
        type: "FEATURE" as ChangeType,
        title: "Offline mode with automatic sync",
        description: "Work without internet, sync when you reconnect",
        sort_order: 2,
        created_at: "2025-11-10T00:00:00Z",
      },
      {
        id: "item-17",
        entry_id: "entry-4",
        type: "IMPROVEMENT" as ChangeType,
        title: "Push notifications for mentions and deadlines",
        description: null,
        sort_order: 3,
        created_at: "2025-11-10T00:00:00Z",
      },
    ],
  },
]

export function getDemoData() {
  return {
    profile: mockProfile,
    product: mockProduct,
    entries: mockEntries,
  }
}
